# #####################################################################
# Automatically generated by qmake (2.01a) Wed Jan 27 15:12:59 2010
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . \
               ../../common

# Input
SOURCES += main.cpp \
           mainwindow.cpp \
           ../../common/databasenetworkaccessmanager.cpp
HEADERS += mainwindow.h
FORMS += mainwindow.ui
QT += webkit sql network
